/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import java.awt.Image;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Admin
 */
public class Inicio extends javax.swing.JPanel {

    /**
     * Creates new form Inicio
     */
    public Inicio() {
        try {
            initComponents();
            Date dia = new Date();
            SimpleDateFormat formato = new SimpleDateFormat("dd");
            Date mes = new Date();
            SimpleDateFormat formato2 = new SimpleDateFormat("MM");
            Date anio = new Date();
            SimpleDateFormat formato3 = new SimpleDateFormat("YYYY");
            jLabel7.setText("Hoy es " + formato.format(dia) + " del " + "Marzo" + " de " + formato3.format(anio));

            ImageIcon imagen2 = new ImageIcon("src/img/paquete.jpg");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel7.setBackground(new java.awt.Color(51, 153, 255));

        jLabel7.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(458, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setForeground(new java.awt.Color(102, 102, 102));
        jLabel10.setText(" el Flujo de envío de Paquetes, Control de Flota de Vehículo…");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 170, 590, 20));

        jLabel8.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Bienvenido");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 100, 170, 60));

        jLabel12.setForeground(new java.awt.Color(102, 102, 102));
        jLabel12.setText("Esta herramienta nos permite llevar un control completo y detallado de su Empresa, tendrá acceso");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 220, 700, 30));

        jLabel9.setForeground(new java.awt.Color(102, 102, 102));
        jLabel9.setText("A HispaTrans, Software de Gestión orientado a Empresas de Paquetería para Administrar de Forma Óptima y Fácil");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(69, 150, 680, 30));

        jLabel17.setForeground(new java.awt.Color(102, 102, 102));
        jLabel17.setText(" a herramientas especiales para tareas específicas, como lo son:");
        jPanel3.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 241, -1, -1));

        jLabel18.setForeground(new java.awt.Color(102, 102, 102));
        jLabel18.setText("- Registrar envíos (Paquetes).");
        jPanel3.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 270, 400, -1));

        jLabel20.setForeground(new java.awt.Color(102, 102, 102));
        jLabel20.setText("- Controlar la flota de Vehículos de Transporte (Camiones).");
        jPanel3.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 330, 350, -1));

        jLabel19.setForeground(new java.awt.Color(102, 102, 102));
        jLabel19.setText("- Registrar nuevos trabajadores (Camioneros).");
        jPanel3.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 300, -1, -1));

        jLabel21.setForeground(new java.awt.Color(102, 102, 102));
        jLabel21.setText("- Ver que Vehículos de Transporte, tiene asignado cada Trabajador (Camionero).");
        jPanel3.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 360, 450, -1));

        jLabel22.setForeground(new java.awt.Color(102, 102, 102));
        jLabel22.setText("- Búsqueda Avanzada de Envíos por Camionero (DNI) o Fecha de Envio (Paquete).");
        jPanel3.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 390, 450, -1));

        jLabel23.setForeground(new java.awt.Color(102, 102, 102));
        jLabel23.setText("- Editar y Eliminar cualquier tipo de Registro.");
        jPanel3.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 420, 440, -1));

        jPanel8.setBackground(new java.awt.Color(51, 153, 255));

        jLabel11.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(465, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 930, 630));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 930, 630));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    // End of variables declaration//GEN-END:variables
}
