/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import controller.ControladorPaquete;
import javax.swing.JOptionPane;
import javax.swing.JOptionPane;
import modelo.TableModelPaquete;
import controller.ControladorPaquete;
import java.awt.Color;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JMenuItem;
import javax.swing.JPopupMenu;
import modelo.ModeloProvincia;

/**
 *
 * @author FER
 */
public class PaqueteT extends javax.swing.JPanel {

    TableModelPaquete tabla2 = ControladorPaquete.getT3();

    /**
     * Creates new form PaqueteT
     */
    public PaqueteT() {
        initComponents();
        tabla.getTableHeader().setFont(new Font("Segoe UI", Font.PLAIN, 12));
        tabla.getTableHeader().setOpaque(false);
        tabla.getTableHeader().setBackground(new Color(32, 136, 203));
        tabla.getTableHeader().setForeground(new Color(0, 0, 0));
        tabla.setRowHeight(25);
        this.popupMetodo();
        try {
            ControladorPaquete.obtenerPaquete();
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        descripcion = new javax.swing.JTextField();
        codigo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        limpiar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        fecha = new javax.swing.JTextField();
        cod_provincia = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        dni_camionero = new javax.swing.JTextField();
        direccion = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        destinatario = new javax.swing.JTextField();
        bAvanzada = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();

        jPanel2.setBackground(new java.awt.Color(102, 153, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Código: ");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, -1, -1));
        jPanel2.add(descripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, 88, -1));
        jPanel2.add(codigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, 100, -1));
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(117, 110, -1, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Destinatario:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 40, -1, 20));

        jLabel3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Descripción: ");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, -1, 20));

        jLabel5.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Dirección:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 90, -1, 20));

        limpiar.setText("Limpiar");
        limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpiarActionPerformed(evt);
            }
        });
        jPanel2.add(limpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 130, -1, -1));

        jLabel6.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Fecha:");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 40, -1, 20));

        jButton1.setText("Añadir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 130, -1, -1));

        fecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fechaActionPerformed(evt);
            }
        });
        jPanel2.add(fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 40, 110, -1));
        jPanel2.add(cod_provincia, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 40, 90, -1));

        jLabel8.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Dni_Camionero:");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 90, -1, 20));
        jPanel2.add(dni_camionero, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 90, 91, -1));
        jPanel2.add(direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 90, 110, -1));

        jLabel7.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Cod_Provincia:");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 40, -1, 20));
        jPanel2.add(destinatario, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 40, 88, -1));

        bAvanzada.setText("Búsqueda Avanzada");
        bAvanzada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAvanzadaActionPerformed(evt);
            }
        });
        jPanel2.add(bAvanzada, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 130, 160, -1));

        tabla.setModel(tabla2);
        jScrollPane2.setViewportView(tabla);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 930, 510));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 930, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 690, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpiarActionPerformed
        codigo.setText("");
        descripcion.setText("");
        destinatario.setText("");
        direccion.setText("");
        fecha.setText("");
        cod_provincia.setText("");
        dni_camionero.setText("");
    }//GEN-LAST:event_limpiarActionPerformed

    public void popupMetodo() {
        JPopupMenu popupMenu = new JPopupMenu();
        JMenuItem menuItem1 = new JMenuItem("Editar");
        JMenuItem menuItem2 = new JMenuItem("Eliminar");
        JMenuItem menuItem3 = new JMenuItem("Ver Provincia");
        // EDITAR: Al hacer click se cogera esa fila selecionada y con los getters
        // extraigo los datos
        menuItem1.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                try {
                    int index = tabla.getSelectedRow();
                    int codigo = Integer.parseInt(tabla.getValueAt(index, 0).toString());
                    String descripcion = tabla.getValueAt(index, 1).toString();
                    String destinatario = tabla.getValueAt(index, 2).toString();
                    String direccion = tabla.getValueAt(index, 3).toString();
                    String fecha = tabla.getValueAt(index, 4).toString();
                    String dni_camionero = tabla.getValueAt(index, 5).toString();
                    int cod_provincia = Integer.parseInt(tabla.getValueAt(index, 6).toString());

                    // Hacer visible el JFrame de editar
                    PaqueteEditar PE = new PaqueteEditar(codigo, descripcion, destinatario, direccion, fecha, dni_camionero, cod_provincia);
                    PE.setVisible(true);
                } catch (Exception t) {
                    JOptionPane.showMessageDialog(null, t);
                }
            }
        });
        // ELIMINAR: Lo mismo que editar solo que aqui no hay jFrame le paso el metodo
        // de eliminar y recargar la tabla
        menuItem2.addActionListener(
                new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                try {
                    int index = tabla.getSelectedRow();
                    int codigo = Integer.parseInt(tabla.getValueAt(index, 0).toString());
                    String descripcion = tabla.getValueAt(index, 1).toString();
                    String destinatario = tabla.getValueAt(index, 2).toString();
                    String direccion = tabla.getValueAt(index, 3).toString();
                    String fecha = tabla.getValueAt(index, 4).toString();
                    String dni_camionero = tabla.getValueAt(index, 5).toString();
                    int cod_provincia = Integer.parseInt(tabla.getValueAt(index, 5).toString());

                    ControladorPaquete.eliminarPaquete(codigo);
                    //JOptionPane.showMessageDialog(null, "Paquete eliminado");
                } catch (Exception y) {
                    JOptionPane.showMessageDialog(null, y);
                }
            }
        });
        menuItem3.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                try {
                    int index = tabla.getSelectedRow();
                    int cod_provincia = Integer.parseInt(tabla.getValueAt(index, 6).toString());
                    ModeloProvincia.obtenerProvincias(cod_provincia);
                } catch (Exception t) {
                    JOptionPane.showMessageDialog(null, t);
                }
            }
        });
        // Añadir los addActionListener al menu creado
        popupMenu.add(menuItem1);
        popupMenu.add(menuItem2);
        popupMenu.add(menuItem3);
        // Los añadimos a la tabla
        tabla.setComponentPopupMenu(popupMenu);
    }

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            int cod = Integer.parseInt(codigo.getText());
            String desc = descripcion.getText();
            String dest = destinatario.getText();
            String dir = direccion.getText();
            String date = fecha.getText();
            String dcamionero = dni_camionero.getText();
            int cprovincia = Integer.parseInt(cod_provincia.getText());
            ControladorPaquete.insertarPaquete(cod, desc, dest, dir, date, dcamionero, cprovincia);
            JOptionPane.showMessageDialog(null, "Paquete almacenado");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void fechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fechaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fechaActionPerformed

    private void bAvanzadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAvanzadaActionPerformed
        CamioneroFecha VE = new CamioneroFecha();
        VE.setVisible(true);
    }//GEN-LAST:event_bAvanzadaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAvanzada;
    private javax.swing.JTextField cod_provincia;
    private javax.swing.JTextField codigo;
    private javax.swing.JTextField descripcion;
    private javax.swing.JTextField destinatario;
    private javax.swing.JTextField direccion;
    private javax.swing.JTextField dni_camionero;
    private javax.swing.JTextField fecha;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton limpiar;
    private javax.swing.JTable tabla;
    // End of variables declaration//GEN-END:variables
}
